### ISSUE TITLE
`dispatch-sync` within event handler warning

### ISSUE THREAD

**Issue by jeaye** [Day8/re-frame-test#10]
>   Think of it kind of as though every `dispatch` in your app had been magically
>  turned into `dispatch-sync`, and re-frame had lifted the restriction that says
>  you can't call `dispatch-sync` from within an event handler.

From  https://github.com/Day8/re-frame-test/blob/67cc505942693989fb2d23f76d256ee1ad6cb45c/src/day8/re_frame/test.cljc#L294

Yet, in my synchronous tests, I'm seeing this:

```text
re-frame: while handling "[:lets-bet.client.mobile.navigation.events/navigate {:lets-bet.client.mobile.navigation.spec/key :lets-bet.client.mobile.navigation.spec/loading, :lets-bet.client.mobile.navigation.spec/routeName :lets-bet.client.mobile.navigation.spec/loading}]", dispatch-sync was called for "[:lets-bet.client.mobile.notification.events/start-timers]". You can't call dispatch-sync within an event handler.
```

The dispatch itself is not a dispatch-sync, but is being turned into one. Am I safe?

**Comment by stumitchell** [comment]
Hmm, I suspect there may be a problem in your code as re-frame-test doesn't actually turn `dispatch` into `dispatch-sync` what it does is rebind the re-frame router.

Search your code for `dispatch-sync` and see what turns up.

**Comment by jeaye** [comment]
In my entire source, I only have two instances of `dispatch-sync`, right next to each other:

```clj
(reg-spec-event-db
  ::initialize-db
  ([db]
   d/app-db)
  {:args [:db ::d/app-db]})

(defn initialize-db []
  (dispatch-sync [::initialize-db])
  (dispatch-sync [::nav.events/navigate {::nav.spec/key ::nav.spec/loading
                                         ::nav.spec/routeName ::nav.spec/loading}]))

(defn init! []
  (st/instrument)
  (initialize-db))
```

As you can see from the error, the issue happens when hitting a `dispatch` triggered by the `::nav.events/navigate` event. I'm 100% positive that I'm not doing any other calls to `dispatch-sync`.

**Comment by jeaye** [comment]
If I call the same code from within an async test handler, there is no warning, so this very much appears to be related to `rf-test/run-test-sync`.

**Comment by stumitchell** [comment]
Ok I've looked at the code and it appears I was mistaken, I'll need to have a closer look

**Comment by jeaye** [comment]
Not a problem! I appreciate the quick support. :) I'll see what more I can find as well.

**Comment by jeaye** [comment]
You'll know more about this code than me, but I *think* that we might be able to resolve this by also rebinding `rf/dispatch-sync` to `new-dispatch` here: https://github.com/Day8/re-frame-test/blob/67cc505942693989fb2d23f76d256ee1ad6cb45c/src/day8/re_frame/test.cljc#L283

What do you think?

**Comment by jeaye** [comment]
Any update on this?

**Comment by samroberton** [comment]
Sorry, I didn't see this issue earlier.

I suspect that yes, you could get right of this warning by rebinding `rf/dispatch-sync` to `new-dispatch` -- but bear in mind that since `new-dispatch` itself calls `rf/dispatch-sync`, you'd need to capture the value of the latter before rebinding, to make sure that `new-dispatch` still called the original value.

If you did that, though, the change would allow your tests to call `dispatch-sync` within a `dispatch-sync`, even though in real life, you're not allowed to do that.  Is that a good trade-off for suppressing the warning?

Also worth bearing in mind:  you only see this warning when you have an event handler (here, the `::nav.events/navigate` handler) which calls `dispatch` (here, dispatching `:start-timers`).  Calling `dispatch` from an event handler has always seemed like a code smell to me (though I'm aware plenty of people don't share this opinion):  it feels like broadening the definition of an "event" to include "some control flow internal to my app which _isn't_ actually triggered by an external input, but where I can't be bothered directly calling a function, so I'm just going to throw something on `re-frame`'s event queue because it's there".

**Comment by jeaye** [comment]
I'm gonna close this one; my primary concern was whether or not this warning meant things were going to be broken, at least to the point where they don't behave the same way as my app. From what I gather, that's not the case, and I appreciate the detailed input and suggestions regarding the clean up of dispatching within event handlers.
