### ISSUE TITLE
7/13 tests executed

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-test#6]
When the tests are run, Karma says:

```
Chrome 58.0.3029 (Mac OS X 10.12.4): Executed 7 of 13 SUCCESS (0.116 secs / 0.188 secs)
```

I'm not exactly sure why we only have half of the tests executing. @samroberton do you remember anything about this?

**Comment by samroberton** [comment]
There are in fact only 7 tests that are executable in ClojureScript in the `day8.re-frame.test-reframe.test-test` namespace.  So I think the actual question is "why does Karma think that there are 13 tests when in fact there are only 7?"

I think the answer to that probably lies in the horrible things that `day8.re-frame.test-reframe.macros/assert-captured-test-results` has to do in order to be create a realistic test.

The difficulty comes from the fact that what we *really* want our tests to test is "when I write a `deftest` form in my application's test suite, using `re-frame-test` functionality within that test, will my test pass or fail correctly?".  Which means that we want tests that have, inside them, `deftest` forms, and which assert that the processing of those `deftest` forms is handled correctly.

Unfortunately, the design of `clojure.test` is not what one might call a particularly FP approach to the problem.  So our test suite here has to delve into the bowels of `clojure.test`'s side-effecty horridness in order to track the execution of the inner `deftest`.  I assume that Karma is doing its own delving into the bowels of `clojure.test` in order to track which tests are executing, and my guess is that Karma's test count double-counts the 6 tests which are not JVM-only and which use `assert-captured-test-results`.  That is, Karma is counting once (correctly) for the `deftest` that is our test suite's test, but then additionally (unintentionally) counting the occurrence of the `deftest` form which appears in the macro-expanded test as an example of the sort of test that `re-frame-test` allows you to write (an example whose reporting we're testing).

Without spending time in the Karma codebase, I don't know what we'd need to do to stop Karma's test count from seeing the inner `deftest` forms.
